<?php
/**
 * The side hamburger menu navigation
 *
 * This is the template that displays the side menu hamburger
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package wp_rig
 */

namespace WP_Rig\WP_Rig;

?>

	<nav id="side-hamburger-nav" role="navigation">
		<div class="hamburger-top-header">
			<div class="nav-burger"><div class="burger"></div> </div><!-- end div.nav-burger -->
		</div><!-- end div.top-header -->

		<ul id="hamburger-vertical-menu-list" class="nav">
			<!-- This part is the navigation generated by WordPress.  -->
			<!-- links to the 8 most recent projects, if on a project page, then make sure this one isn't part of it -->
			<?= implode( "\n\t\t\t", wp_rig()->get_project_sidemenu_items( 8 ) ); ?>
		</ul><!-- end ul#menu-vertical-menu-->
	</nav><!-- end nav#side-hamburger-nav -->





