<?php
/**
 * The header for our theme
 *
 * This is the template that displays all of the <head> section and everything up until <div id="content">
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package wp_rig
 */

namespace WP_Rig\WP_Rig;

?>
<!doctype html>
<html <?php language_attributes(); ?> class="no-js">
<head>
	<meta charset="<?php bloginfo( 'charset' ); ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
	<link rel="profile" href="http://gmpg.org/xfn/11">

	<?php
	if ( ! wp_rig()->is_amp() ) {
		?>
		<script>document.documentElement.classList.remove( 'no-js' );</script>
		<?php
	}
	?>

	<?php wp_head(); ?>
</head>
<?php
wp_rig()->print_styles( 'wp-rig-front-page' );
?>
<body class="experimental">
<?php wp_body_open(); ?>

<header class="banner" id="main-header" role="banner">

	<nav role="navigation">
		<div class="top-header">
			<div class="nav-burger">
				<div class="burger"></div>
			</div>
		</div>



	<!-- This part is the navigation generated by WordPress.  -->
		<ul id="menu-vertical-menu" class="nav">
<!-- links to the 8 most recent projects, if on a project page, then make sure this one isn't part of it -->
		<?= implode( '', wp_rig()->get_project_sidemenu_items( 8 ) ); ?>

		</ul>
	</nav>

</header>



<div id="experimental-page" class="site experimental">


